#!/home/dd/anaconda3/bin/python

"""cle (GnuPG) clipboard encryption (github.com/taext/cle)"""

######################################################
#                                                    #
#               cle v3.0 (October 2020)              #
#                                                    #
#  What's New: Add error message bug fix             #
#                                                    #
#                                                    #
######################################################

import gnupg
import sys
import clipboard
import gnupg._parsers

# monkey patch from https://github.com/isislovecruft/python-gnupg/issues/207
gnupg._parsers.Verify.TRUST_LEVELS["ENCRYPTION_COMPLIANCE_MODE"] = 23

def main(clear_text,
         pubkey_file_name='pubkey.asc',
         pubkey_file_path='/path/to/pubkey/'):

    """Takes cleartext string, optionally pubkey file name
       and file path, returns PGP-encrypted string."""

    gpg = gnupg.GPG()
    key_data = open(pubkey_file_path + pubkey_file_name).read()

    import_result = gpg.import_keys(key_data)
    fingerprint = import_result.results[0]['fingerprint']

    encr_data = gpg.encrypt(clear_text, fingerprint)
    result = str(encr_data)

    return result


if __name__ == '__main__':

    args = clipboard.paste()
    result = main(args)
    clipboard.copy(result)
    #print(f"result: {result}")
    #print(f"clipboard: {clipboard.paste()}")    
