#!/home/dd/anaconda3/bin/python

"""GnuPG encryption module - pipe version. (github.com/taext/gm2)"""

######################################################
#                                                    #
#               gm2 v2.4 (July 23rd 2017)            #
#                                                    #
#  What's New: Moved '/' from (26) to (20)           #
#                                                    #
#                                                    #
######################################################

import gnupg
import sys


def main(clear_text,
         pubkey_file_name='pubkey.asc',
         pubkey_file_path='/home/dd/Documents/pubkeys/'):

    """Takes clear text string, optionally pubkey filename
       and file path, returns PGP-encrypted string."""

    gpg = gnupg.GPG()
    key_data = open(pubkey_file_path + pubkey_file_name).read()

    import_result = gpg.import_keys(key_data)
    fingerprint = import_result.results[0]['fingerprint']

    encr_data = gpg.encrypt(clear_text, fingerprint)
    result = str(encr_data)

    return result


if __name__ == '__main__':

    args = sys.stdin.read()
    print(main(args))
    