#!/home/dd/anaconda3/bin/python

"""GnuPG encryption module."""

######################################################
#                                                    #
#               gme v1.6 (July 22nd 2017)            #
#                                                    #
#  What's New: changed gmg_me() to gpgme()           #
#                                                    #
######################################################


import gnupg
import sys
import os

def gpgme(clear_text,
           pubkey_file_name='pubkey.asc',
           pubkey_file_path='/home/dd/Documents/pubkeys'):

    """Takes clear text string, optional pubkey filename
    and file path, returns GPG encrypted string."""

    gpg = gnupg.GPG()
    os.chdir(pubkey_file_path)
    key_data = open(pubkey_file_name).read()

    import_result = gpg.import_keys(key_data)
    fingerprint = import_result.results[0]['fingerprint']

    encr_data = gpg.encrypt(clear_text, fingerprint)
    result = str(encr_data)

    return result

if __name__ == '__main__':

    args = []
    [args.append(item) for item in sys.argv[1:]]
    print(gpgme(*args))
    